import type {
  ExchangeInfo,
  FiatCurrencyInfo,
  Stablecoin,
  Chain,
} from "./types";

export const FIAT_CURRENCIES: FiatCurrencyInfo[] = [
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸" },
  { code: "KRW", name: "Korean Won", symbol: "₩", flag: "🇰🇷" },
  { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧" },
];

export const STABLECOINS: { id: Stablecoin; name: string; coingeckoId: string }[] = [
  { id: "USDT", name: "Tether", coingeckoId: "tether" },
  { id: "USDC", name: "USD Coin", coingeckoId: "usd-coin" },
  { id: "DAI", name: "Dai", coingeckoId: "dai" },
];

export const CHAINS: { id: Chain; name: string }[] = [
  { id: "ERC-20", name: "Ethereum (ERC-20)" },
  { id: "TRC-20", name: "Tron (TRC-20)" },
  { id: "SOL", name: "Solana" },
  { id: "Arbitrum", name: "Arbitrum" },
  { id: "Base", name: "Base" },
  { id: "Polygon", name: "Polygon" },
];

export const EXCHANGES: ExchangeInfo[] = [
  {
    id: "binance",
    name: "Binance",
    country: "Global",
    supportedFiat: ["USD", "KRW", "EUR", "GBP"],
    supportedStablecoins: ["USDT", "USDC", "DAI"],
    tradingFee: { maker: 0.001, taker: 0.001 },
    spreadEstimate: 0.0005,
    fxMarkup: 0.001,
    withdrawalFees: {
      "ERC-20": { USDT: 3.0, USDC: 3.0, DAI: 3.0 },
      "TRC-20": { USDT: 1.0, USDC: 1.0 },
      SOL: { USDT: 1.0, USDC: 1.0 },
      Arbitrum: { USDT: 0.5, USDC: 0.5 },
      Base: { USDT: 0.5, USDC: 0.5 },
      Polygon: { USDT: 0.5, USDC: 0.5 },
    },
    depositMethods: ["Bank Transfer", "Card", "P2P"],
    processingTime: "10-30 min",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    country: "US",
    supportedFiat: ["USD", "KRW", "EUR", "GBP"],
    supportedStablecoins: ["USDT", "USDC", "DAI"],
    tradingFee: { maker: 0.004, taker: 0.006 },
    spreadEstimate: 0.005,
    fxMarkup: 0.002,
    withdrawalFees: {
      "ERC-20": { USDT: 5.0, USDC: 0, DAI: 5.0 },
      Arbitrum: { USDT: 0.5, USDC: 0 },
      Base: { USDT: 0, USDC: 0 },
      Polygon: { USDT: 0.5, USDC: 0 },
      SOL: { USDT: 1.0, USDC: 0.5 },
    },
    depositMethods: ["Bank Transfer", "Card"],
    processingTime: "Instant - 5 min",
  },
  {
    id: "bybit",
    name: "Bybit",
    country: "Global",
    supportedFiat: ["USD", "KRW", "EUR", "GBP"],
    supportedStablecoins: ["USDT", "USDC", "DAI"],
    tradingFee: { maker: 0.001, taker: 0.001 },
    spreadEstimate: 0.0008,
    fxMarkup: 0.0015,
    withdrawalFees: {
      "ERC-20": { USDT: 3.5, USDC: 5.0, DAI: 5.0 },
      "TRC-20": { USDT: 1.0, USDC: 1.5 },
      SOL: { USDT: 1.0, USDC: 1.0 },
      Arbitrum: { USDT: 0.5, USDC: 0.5 },
      Polygon: { USDT: 0.5, USDC: 0.5 },
    },
    depositMethods: ["Bank Transfer", "Card", "P2P"],
    processingTime: "10-30 min",
  },
  {
    id: "kraken",
    name: "Kraken",
    country: "US",
    supportedFiat: ["USD", "KRW", "EUR", "GBP"],
    supportedStablecoins: ["USDT", "USDC", "DAI"],
    tradingFee: { maker: 0.0016, taker: 0.0026 },
    spreadEstimate: 0.001,
    fxMarkup: 0.001,
    withdrawalFees: {
      "ERC-20": { USDT: 2.5, USDC: 2.5, DAI: 2.5 },
      "TRC-20": { USDT: 1.0 },
      SOL: { USDT: 1.0, USDC: 0.5 },
      Arbitrum: { USDT: 0.5, USDC: 0.3 },
      Polygon: { USDT: 0.5, USDC: 0.3 },
    },
    depositMethods: ["Bank Transfer", "Card"],
    processingTime: "1-5 min",
  },
  {
    id: "okx",
    name: "OKX",
    country: "Global",
    supportedFiat: ["USD", "KRW", "EUR", "GBP"],
    supportedStablecoins: ["USDT", "USDC", "DAI"],
    tradingFee: { maker: 0.0008, taker: 0.001 },
    spreadEstimate: 0.0005,
    fxMarkup: 0.001,
    withdrawalFees: {
      "ERC-20": { USDT: 3.0, USDC: 3.0, DAI: 5.0 },
      "TRC-20": { USDT: 0.8, USDC: 0.8 },
      SOL: { USDT: 0.5, USDC: 0.5 },
      Arbitrum: { USDT: 0.3, USDC: 0.3 },
      Base: { USDT: 0.3, USDC: 0.3 },
      Polygon: { USDT: 0.3, USDC: 0.3 },
    },
    depositMethods: ["Bank Transfer", "Card", "P2P"],
    processingTime: "10-30 min",
  },
  {
    id: "upbit",
    name: "Upbit",
    country: "KR",
    supportedFiat: ["KRW"],
    supportedStablecoins: ["USDT", "USDC"],
    tradingFee: { maker: 0.0005, taker: 0.0005 },
    spreadEstimate: 0.002,
    fxMarkup: 0.015,
    withdrawalFees: {
      "ERC-20": { USDT: 5.0, USDC: 5.0 },
      "TRC-20": { USDT: 1.0 },
      SOL: { USDT: 1.0, USDC: 1.0 },
      Arbitrum: { USDT: 1.0 },
    },
    depositMethods: ["Bank Transfer (KRW)"],
    processingTime: "Instant - 10 min",
  },
  {
    id: "bithumb",
    name: "Bithumb",
    country: "KR",
    supportedFiat: ["KRW"],
    supportedStablecoins: ["USDT", "USDC"],
    tradingFee: { maker: 0.0004, taker: 0.0004 },
    spreadEstimate: 0.003,
    fxMarkup: 0.018,
    withdrawalFees: {
      "ERC-20": { USDT: 5.0, USDC: 5.0 },
      "TRC-20": { USDT: 1.0 },
      SOL: { USDT: 1.5 },
    },
    depositMethods: ["Bank Transfer (KRW)"],
    processingTime: "Instant - 10 min",
  },
];

export const DEFAULT_AMOUNT: Record<string, number> = {
  USD: 1000,
  KRW: 1000000,
  EUR: 1000,
  GBP: 1000,
};
